### ISSUE TITLE
Modularizar views

### ISSUE THREAD

**Issue by Emiliemorais** [DAS1-2016/Finpy#15]
Verificar possibilidade de utilizar _class-based_ views para implementar os tipos de requisições (post, get, update, etc...) ao invés de utilizar if's, onde fizer necessário.

**Comment by italopaiva** [comment]
Criar um mixin para colocar os métodos em comum de views (check_extra_content(), por exemplo).

**Comment by italopaiva** [comment]
Testar as novas views.

Rodar os testes: `python3 manage.py test`
